### PR TITLE
Adds a method for processing Custom templates a bit more intuitive

### PR DESCRIPTION
**Pull request by mikewoudenberg**
Hey, I worked on this a bit, to be able to use custom templates a bit more intuitive. It'll represent the indiviual sections of a custom template as individual files with the correct filetype so you can have some syntax highlighting in there. Not sure whether it's worthwhile for your usecase, but thought I might as well share it. 

Screenshot of the extension in action:
Screenshot 2024-03-07 at 21 22 43

### CODE REVIEW

**Comment by 1nVitr0** [comment]
Looks great! To be hones, I didn't really expect this to be useful for anyone else. I will definitely look through this, though it might take me a while. If this is still open in April and you come across it, shoot me a message. I may have forgotten about it then

**Comment by JohnLindahlTech** [comment]
It is now may, and this looks like a cool thing to add.

**Comment by 1nVitr0** [comment]
@JohnLindahlTech @mikewoudenberg Very sorry for the late response. I believe I looked at this and then simply lost track. If I haven't got that merged by the end of next week (11th of may), just shoot me a few messages.

**Comment by 1nVitr0** [comment]
I haven't forgotten about this (again). I am in the process of adding some basic test cases that should be done soon.

I may adjust this pull requests commit messages for the changelog generation, just as a heads-up

**Comment by 1nVitr0** [comment]
@mikewoudenberg @JohnLindahlTech Merging now, sorry for the long delay. Had to plow my way through the tests in #7 first.

**Comment by mikewoudenberg** [comment]
Thanks for pulling through. Glad it was valuable to someone :)

**Pull request merged**
